fundamentus_base = "https://www.fundamentus.com.br/"
fundamentus = "https://www.fundamentus.com.br/detalhes.php"
dados_de_mercado = "https://www.dadosdemercado.com.br/bolsa/acoes"
dados_de_mercado_base = "https://www.dadosdemercado.com.br/"
API_dados_de_mercado = "https://api.dadosdemercado.com.br/v1"